apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot-app
  namespace: application
  labels:
    app: springboot-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: springboot-app

  template:
    metadata:
      labels:
        app: springboot-app

    spec:
      containers:
      - name: springboot-container
        image: daneshkabade45/springboot-enterprise-app:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"